CREATE TABLE restaurants
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    address VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_restaurant PRIMARY KEY (id)
);