CREATE TABLE dishes
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    is_available BOOLEAN NOT NULL,
    restaurant_id BIGINT NOT NULL,

    CONSTRAINT pk_dishes PRIMARY KEY (id),

    CONSTRAINT fk_dish_restaurant
        FOREIGN KEY (restaurant_id) REFERENCES restaurants(id)
);