CREATE TABLE processed_events
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id     BIGINT                                  NOT NULL,
    new_status   VARCHAR(255)                            NOT NULL,
    processed_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_processed_events PRIMARY KEY (id),
    CONSTRAINT uk_processed_events_order_status UNIQUE (order_id, new_status)
);