name: Spring boot CI

on:
  pull_request:
    branches: [ master ]

jobs:
  check-tasks:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
      SPRING_MAIL_HOST: ${{ secrets.SPRING_MAIL_HOST }}
      SPRING_MAIL_PORT: ${{ secrets.SPRING_MAIL_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven Wrapper executable
        run: chmod +x ./mvnw

      - name: Run Spring app tests
        run: ./mvnw -B clean test
